[versions]

[libraries]
androidx-activity-compose = "androidx.activity:activity-compose:1.6.1"
androidx-core-ktx = "androidx.core:core-ktx:1.9.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"


[plugins]

[bundles]

